name: Master
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.15"
      - run: pip install --user -e '.[dev]'
      - run: PYTHONPATH=. pytest tests
      - run: git config --global user.name "github-actions"
      - run: git config --global user.email "action@github.com"
      - run: pip install twine==3.8.0
      # - name: Setup tmate session
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      #   uses: mxschmitt/action-tmate@v3
      - run: TWINE_USERNAME=__token__ TWINE_PASSWORD=${{ secrets.PYPI_TOKEN }} SKIP=commitizen semantic-release publish
